### ISSUE TITLE
improve readme for server and fix for client

### ISSUE THREAD

**Issue by daniloab** [guilhermedinardi/entria#20]
## server
- [x] improve the `cd` for  `cd entria/server` (less steps redundant) 

## client
- [x] the client is inside a folder called crud, following the readme I got an error
- [x] add `yarn relay` after install and before start
- [x] fix and improve the `cd` for  `cd entria/client/crud` (less steps redundant)

**Comment by guilhermedinardi** [comment]
Done!

**Comment by daniloab** [comment]
so close it =)
